type PaintType = 'base' | 'layer' | 'shade' | 'dry' | 'contrast' | 'auxilliary' | 'air' | 'technical' | 'basing';

type PaintBrand = 'vallejo' | 'gsw';

export interface PaintDbItem {
  name: string;
  hex: string;
  hex2?: string;
  type: PaintType;
  metallic?: boolean;
  gloss?: boolean;
  brand?: PaintBrand;
  image?: string;
}

export const paintDb: PaintDbItem[] = [
  {name: 'Abaddon Black', hex: '#000000', type: 'base'},
  {name: 'Eshin Grey', hex: '#484b4e', type: 'base'},
  {name: 'Mechanicus Standard Grey', hex: '#485052', type: 'base'},
  {name: 'Dawnstone', hex: '#697068', type: 'base'},
  {name: 'Administratum Grey', hex: '#989c94', type: 'base'},
  {name: 'Celestra Grey', hex: '#9fadad', type: 'base'},
  {name: 'Corax White', hex: '#FFFFFF', type: 'base'},
  {name: 'White', hex: '#FFFFFF', brand: 'vallejo', type: 'base'},
  {name: 'Grey Seer', hex: '#919496', type: 'base'},
  {name: 'Averland Sunset', hex: '#e9b929', type: 'base'},
  {name: 'Mephiston Red', hex: '#841710', type: 'base'},
  {name: 'Screamer Pink', hex: '#701e42', type: 'base'},
  {name: 'Daemonette Hide', hex: '#716d88', type: 'base'},
  {name: 'Naggaroth Night', hex: '#423954', type: 'base'},
  {name: 'Caliban Green', hex: '#193c24', type: 'base'},
  {name: 'Wraithbone', hex: '#d3c8a2', type: 'base'},
  {name: 'Leadbelcher', hex: '#4c4d51', hex2: '#FFFFFF', metallic: true, type: 'base'},
  {name: 'Runelord Brass', hex: '#493a2c', hex2: '#FFFFFF', metallic: true, type: 'base'},
  {name: 'Jokaero Orange', hex: '#c52f17', type: 'base'},
  {name: 'Khorne Red', hex: '#5b1201', type: 'base'},
  {name: 'Gal Vorbak Red', hex: '#39172e', type: 'base'},
  {name: 'Barak-Nar Burgundy', hex: '#330f27', type: 'base'},
  {name: 'Phoenician Purple', hex: '#330041', type: 'base'},
  {name: 'Caledor Sky', hex: '#4b6797', type: 'base'},
  {name: 'Macragge Blue', hex: '#283c77', type: 'base'},
  {name: 'Kantor Blue', hex: '#19284f', type: 'base'},
  {name: 'Night Lords Blue', hex: '#021e49', type: 'base'},
  {name: 'Thousand Sons Blue', hex: '#083b59', type: 'base'},
  {name: 'Stegadon Scale Green', hex: '#254460', type: 'base'},
  {name: 'Lupercal Green', hex: '#022120', type: 'base'},
  {name: 'Incubi Darkness', hex: '#294548', type: 'base'},
  {name: 'Death Guard Green', hex: '#5a653c', type: 'base'},
  {name: 'Death World Forest', hex: '#686d35', type: 'base'},
  {name: 'Castellan Green', hex: '#424e28', type: 'base'},
  {name: 'Death Korps Drap', hex: '#2f362b', type: 'base'},
  {name: 'Waaagh! Flesh', hex: '#3c572e', type: 'base'},
  {name: 'Nocturne Green', hex: '#11201f', type: 'base'},
  {name: 'Morghast Bone', hex: '#b29960', type: 'base'},
  {name: 'Zandri Dust', hex: '#a2985d', type: 'base'},
  {name: 'XV-88', hex: '#6f4e25', type: 'base'},
  {name: 'Steel Legion Drab', hex: '#645639', type: 'base'},
  {name: 'Mournfang Brown', hex: '#5a180a', type: 'base'},
  {name: 'Rhinox Hide', hex: '#493735', type: 'base'},
  {name: 'Dryad Bark', hex: '#3b3833', type: 'base'},
  {name: 'Ionrach Skin', hex: '#859371', type: 'base'},
  {name: 'Rakarth Flesh', hex: '#a8a294', type: 'base'},
  {name: 'Ratskin Flesh', hex: '#a26b4c', type: 'base'},
  {name: 'Bugman\'s Glow', hex: '#7e5247', type: 'base'},
  {name: 'Catachan Fleshtone', hex: '#34201b', type: 'base'},
  {name: 'The Fang', hex: '#536579', type: 'base'},
  {name: 'Corvus Black', hex: '#120f10', type: 'base'},
  {name: 'Grey Knights Steel', hex: '#62727d', hex2: '#FFFFFF', metallic: true, type: 'base'},
  {name: 'Iron Hands Steel', hex: '#605a55', hex2: '#FFFFFF', metallic: true, type: 'base'},
  {name: 'Iron Warriors', hex: '#353431', hex2: '#FFFFFF', metallic: true, type: 'base'},
  {name: 'Retributor Armour', hex: '#a26e29', hex2: '#FFFFFF', metallic: true, type: 'base'},
  {name: 'Balthasar Gold', hex: '#6b3f12', hex2: '#FFFFFF', metallic: true, type: 'base'},
  {name: 'Screaming Bell', hex: '#9a4411', hex2: '#FFFFFF', metallic: true, type: 'base'},
  {name: 'Warplock Bronze', hex: '#4f3a3f', hex2: '#FFFFFF', metallic: true, type: 'base'},
  {name: 'Barak-Nar Burgundy', hex: '#451636', type: 'base'},

  {name: 'White Scar', hex: '#FFFFFF', type: 'layer'},
  {name: 'Emperor\'s Children', hex: '#b74073', type: 'layer'},
  {name: 'Xereus Purple', hex: '#47125a', type: 'layer'},
  {name: 'Slaanesh Grey', hex: '#8b8893', type: 'layer'},
  {name: 'Moot Green', hex: '#3cae44', type: 'layer'},
  {name: 'Warpstone Glow', hex: '#0e7029', type: 'layer'},
  {name: 'Screaming Skull', hex: '#b9c099', type: 'layer'},
  {name: 'Ushabti Bone', hex: '#aba172', type: 'layer'},
  {name: 'Nurgling Green', hex: '#7e975e', type: 'layer'},
  {name: 'Fenrisian Grey', hex: '#6d93b3', type: 'layer'},
  {name: 'Stormhost Silver', hex: '#b6bbbe', hex2: '#FFFFFF', metallic: true, type: 'layer'},
  {name: 'Runefang Steel', hex: '#989ea2', hex2: '#FFFFFF', metallic: true, type: 'layer'},
  {name: 'Canoptek Alloy', hex: '#AE9590', hex2: '#FFFFFF', metallic: true, type: 'layer'},
  {name: 'Dark Reaper', hex: '#354d4c', type: 'layer'},
  {name: 'Ulthuan Grey', hex: '#c4ddd5', type: 'layer'},
  {name: 'Dorn Yellow', hex: '#fff55a', type: 'layer'},
  {name: 'Phalanx Yellow', hex: '#ffe200', type: 'layer'},
  {name: 'Flash Gitz Yellow', hex: '#fff300', type: 'layer'},
  {name: 'Yriel Yellow', hex: '#ffd801', type: 'layer'},
  {name: 'Lugganath Orange', hex: '#f69b82', type: 'layer'},
  {name: 'Fire Dragon Bright', hex: '#f4874e', type: 'layer'},
  {name: 'Troll Slayer Orange', hex: '#f16c22', type: 'layer'},
  {name: 'Squig Orange', hex: '#a74d42', type: 'layer'},
  {name: 'Wild Rider Red', hex: '#e82d1b', type: 'layer'},
  {name: 'Evil Sunz Scarlet', hex: '#c01411', type: 'layer'},
  {name: 'Wazdakka Red', hex: '#880803', type: 'layer'},
  {name: 'Word Bearers Red', hex: '#b74073', type: 'layer'},
  {name: 'Fulgrim Pink', hex: '#f3abca', type: 'layer'},
  {name: 'Pink Horror', hex: '#8d2657', type: 'layer'},
  {name: 'Warpfiend Grey', hex: '#66656e', type: 'layer'},
  {name: 'Dechala Lilac', hex: '#b498c9', type: 'layer'},
  {name: 'Kakophoni Purple', hex: '#8869ae', type: 'layer'},
  {name: 'Genestealer Purple', hex: '#7658a5', type: 'layer'},
  {name: 'Blue Horror', hex: '#9eb5ce', type: 'layer'},
  {name: 'Hoeth Blue', hex: '#4c78af', type: 'layer'},
  {name: 'Lothern Blue', hex: '#2c9bcc', type: 'layer'},
  {name: 'Calgar Blue', hex: '#29497f', type: 'layer'},
  {name: 'Teclis Blue', hex: '#3777bf', type: 'layer'},
  {name: 'Alaitoc Blue', hex: '#2e4f85', type: 'layer'},
  {name: 'Altdorf Guard Blue', hex: '#2c4696', type: 'layer'},
  {name: 'Baharroth Blue', hex: '#54bdca', type: 'layer'},
  {name: 'Temple Guard Blue', hex: '#239489', type: 'layer'},
  {name: 'Ahriman Blue', hex: '#00708a', type: 'layer'},
  {name: 'Sotek Green', hex: '#0b6371', type: 'layer'},
  {name: 'Gauss Blaster Green', hex: '#7fc1a5', type: 'layer'},
  {name: 'Sybarite Green', hex: '#17a166', type: 'layer'},
  {name: 'Kabalite Green', hex: '#008962', type: 'layer'},
  {name: 'Elysian Green', hex: '#6b8c37', type: 'layer'},
  {name: 'Ogryn Camo', hex: '#96a648', type: 'layer'},
  {name: 'Straken Green', hex: '#597f1b', type: 'layer'},
  {name: 'Loren Forest', hex: '#486c24', type: 'layer'},
  {name: 'Sons of Horus Green', hex: '#00545e', type: 'layer'},
  {name: 'Vulkan Green', hex: '#223c2e', type: 'layer'},
  {name: 'Skarsnik Green', hex: '#588f6b', type: 'layer'},
  {name: 'Warboss Green', hex: '#307e57', type: 'layer'},
  {name: 'Krieg Khaki', hex: '#bcbb7e', type: 'layer'},
  {name: 'Karak Stone', hex: '#b7945c', type: 'layer'},
  {name: 'Baneblade Brown', hex: '#8e7c68', type: 'layer'},
  {name: 'Gorthor Brown', hex: '#5f463f', type: 'layer'},
  {name: 'Zamesi Desert', hex: '#d89d1a', type: 'layer'},
  {name: 'Tallarn Sand', hex: '#a07407', type: 'layer'},
  {name: 'Deathclaw Brown', hex: '#af634e', type: 'layer'},
  {name: 'Balor Brown', hex: '#875408', type: 'layer'},
  {name: 'Tau Light Ochre', hex: '#bc6b0f', type: 'layer'},
  {name: 'Skrag Brown', hex: '#8b4805', type: 'layer'},
  {name: 'Tuskgor Fur', hex: '#863231', type: 'layer'},
  {name: 'Doombull Brown', hex: '#570003', type: 'layer'},
  {name: 'Pallid Wych Flesh', hex: '#caccbb', type: 'layer'},
  {name: 'Deepkin Flesh', hex: '#a9b79f', type: 'layer'},
  {name: 'Flayed One Flesh', hex: '#eec483', type: 'layer'},
  {name: 'Ungor Flesh', hex: '#d1a560', type: 'layer'},
  {name: 'Kislev Flesh', hex: '#d1a470', type: 'layer'},
  {name: 'Bestigor Flesh', hex: '#cf8951', type: 'layer'},
  {name: 'Cadian Fleshtone', hex: '#c47652', type: 'layer'},
  {name: 'Knight-Questor Flesh', hex: '#996563', type: 'layer'},
  {name: 'Bloodreaver Flesh', hex: '#6a4847', type: 'layer'},
  {name: 'Russ Grey', hex: '#507085', type: 'layer'},
  {name: 'Thunderhawk Blue', hex: '#396a70', type: 'layer'},
  {name: 'Stormvermin Fur', hex: '#6d655f', type: 'layer'},
  {name: 'Skavenblight Dinge', hex: '#45413b', type: 'layer'},
  {name: 'Ironbreaker', hex: '#5d6162', hex2: '#FFFFFF', metallic: true, type: 'layer'},
  {name: 'Liberator Gold', hex: '#b28b49', hex2: '#FFFFFF', metallic: true, type: 'layer'},
  {name: 'Auric Armour Gold', hex: '#e29a36', hex2: '#FFFFFF', metallic: true, type: 'layer'},
  {name: 'Gehenna\'s Gold', hex: '#97420f', hex2: '#fccd31', metallic: true, type: 'layer'},
  {name: 'Fulgurite Copper', hex: '#954f26', hex2: '#FFFFFF', metallic: true, type: 'layer'},
  {name: 'Hashut Copper', hex: '#7b4d2f', hex2: '#fccd88', metallic: true, type: 'layer'},
  {name: 'Skullcrusher Brass', hex: '#d8a352', hex2: '#FFFFFF', metallic: true, type: 'layer'},
  {name: 'Brass Scorpion', hex: '#713013', hex2: '#f7ba62', metallic: true, type: 'layer'},
  {name: 'Sycorax Bronze', hex: '#866251', hex2: '#FFFFFF', metallic: true, type: 'layer'},
  {name: 'Castellax Bronze', hex: '#723419', hex2: '#FFFFFF', metallic: true, type: 'layer'},


  {name: 'Black Templar', hex: '#050505', hex2: '#636362', type: 'contrast'},
  {name: 'Basilicanum Grey', hex: '#070707', hex2: '#8f8f8e', type: 'contrast'},
  {name: 'Apothecary White', hex: '#91afc9', hex2: '#eef4fa', type: 'contrast'},
  {name: 'Gryph-Charger Grey', hex: '#045177', hex2: '#9abdd0', type: 'contrast'},
  {name: 'Space Wolves Grey', hex: '#043054', hex2: '#7898b4', type: 'contrast'},
  {name: 'Skeleton Horde', hex: '#94855d', hex2: '#e5dbbb', type: 'contrast'},
  {name: 'Aggaros Dunes', hex: '#584f38', hex2: '#beae64', type: 'contrast'},
  {name: 'Cygor Brown', hex: '#33100e', hex2: '#6f4441', type: 'contrast'},
  {name: 'Wyldwood', hex: '#3c211a', hex2: '#674c47', type: 'contrast'},
  {name: 'Snakebite Leather', hex: '#5a462f', hex2: '#a66613', type: 'contrast'},
  {name: 'Gore-Grunta Fur', hex: '#563925', hex2: '#863f07', type: 'contrast'},
  {name: 'Fyreslayer Flesh', hex: '#604332', hex2: '#b77563', type: 'contrast'},
  {name: 'Guilliman Flesh', hex: '#923023', hex2: '#cc988b', type: 'contrast'},
  {name: 'Darkoath Flesh', hex: '#895451', hex2: '#cb8e7e', type: 'contrast'},
  {name: 'Flesh Tearers Red', hex: '#3d0100', hex2: '#7f0c09', type: 'contrast'},
  {name: 'Blood Angels Red', hex: '#78080c', hex2: '#bb1318', type: 'contrast'},
  {name: 'Volupus Pink', hex: '#580014', hex2: '#89023d', type: 'contrast'},
  {name: 'Gryph-Hound Orange', hex: '#842705', hex2: '#df5b30', type: 'contrast'},
  {name: 'Iyanden Yellow', hex: '#d46e04', hex2: '#f7c024', type: 'contrast'},
  {name: 'Nazdreg Yellow', hex: '#593e00', hex2: '#c58c00', type: 'contrast'},
  {name: 'Dark Angels Green', hex: '#000202', hex2: '#01473f', type: 'contrast'},
  {name: 'Warp Lightning', hex: '#00511c', hex2: '#00914a', type: 'contrast'},
  {name: 'Ork Flesh', hex: '#01501b', hex2: '#007e29', type: 'contrast'},
  {name: 'Creed Camo', hex: '#095524', hex2: '#528b68', type: 'contrast'},
  {name: 'Militarum Green', hex: '#626f04', hex2: '#929746', type: 'contrast'},
  {name: 'Plaguebearer Flesh', hex: '#5d6e08', hex2: '#bfc697', type: 'contrast'},
  {name: 'Leviadon Blue', hex: '#010407', hex2: '#01284f', type: 'contrast'},
  {name: 'Ultramarines Blue', hex: '#010c3a', hex2: '#264b81', type: 'contrast'},
  {name: 'Talassar Blue', hex: '#002e5b', hex2: '#006eba', type: 'contrast'},
  {name: 'Aethermatic Blue', hex: '#026f84', hex2: '#7ab7c3', type: 'contrast'},
  {name: 'Akhelian Green', hex: '#004759', hex2: '#007795', type: 'contrast'},
  {name: 'Terradon Turquoise', hex: '#004c54', hex2: '#008398', type: 'contrast'},
  {name: 'Shyish Purple', hex: '#200239', hex2: '#503864', type: 'contrast'},
  {name: 'Magos Purple', hex: '#682559', hex2: '#bc9ebc', type: 'contrast'},

  // New Contrasts
  {name: 'Doomfire Magenta', hex: '#ad0067', hex2: '#df0084', type: 'contrast'},
  {name: 'Imperial Fist', hex: '#faa31b', hex2: '#fdb714', type: 'contrast'},
  {name: 'Luxion Purple', hex: '#2b0450', hex2: '#401a70', type: 'contrast'},
  {name: 'Sigvald Burgundy', hex: '#5e004a', hex2: '#7c0052', type: 'contrast'},
  {name: 'Dreadful Visage', hex: '#8d7391', hex2: '#dac8d6', type: 'contrast'},
  {name: 'Garaghak\'s Sewer', hex: '#534333', hex2: '#875d1c', type: 'contrast'},
  {name: 'Ratling Grime', hex: '#474341', hex2: '#867f7d', type: 'contrast'},
  {name: 'Aeldari Emerald', hex: '#005d5b', hex2: '#008370', type: 'contrast'},
  {name: 'Kroxigor Scales', hex: '#006075', hex2: '#0094a5', type: 'contrast'},
  {name: 'Frostheart', hex: '#006c9c', hex2: '#00405c', type: 'contrast'},


  {name: 'Cassandora Yellow', hex: '#e8843a', hex2: '#fbe9b4', type: 'shade'},
  {name: 'Fuegan Orange', hex: '#712107', hex2: '#d99863', type: 'shade'},
  {name: 'Carroburg Crimson', hex: '#390f10', hex2: '#f3aedf', type: 'shade'},
  {name: 'Druchii Violet', hex: '#2a0f2d', hex2: '#b989bc', type: 'shade'},
  {name: 'Drakenhof Nightshade', hex: '#121b22', hex2: '#dbdde7', type: 'shade'},
  {name: 'Athonian Camoshade', hex: '#262517', hex2: '#f6f7b9', type: 'shade'},
  {name: 'Seraphim Sepia', hex: '#35240c', hex2: '#e0a777', type: 'shade'},
  {name: 'Agrax Earthshade', hex: '#382517', hex2: '#d7cebd', type: 'shade'},
  {name: 'Agrax Earthshade Gloss', hex: '#382517', hex2: '#d7cebd', gloss: true, type: 'shade'},
  {name: 'Nuln Oil', hex: '#1c1c1b', hex2: '#d1cbc9', type: 'shade'},
  {name: 'Cryptek Armourshade Gloss', hex: '#7B5653', hex2: '#D1BDBC', gloss: true, type: 'shade'},
  {name: 'Coelia Greenshade', hex: '#113834', hex2: '#1eb2a7', type: 'shade'},
  {name: 'Biel-Tan Green', hex: '#1a3527', hex2: '#a6d39c', type: 'shade'},
  {name: 'Reikland Fleshshade Gloss', hex: '#371f0e', hex2: '#f3caad', gloss: true, type: 'shade'},
  {name: 'Reikland Fleshshade', hex: '#371f0e', hex2: '#f3caad', type: 'shade'},
  {name: 'Nuln Oil Gloss', hex: '#1c1c1b', hex2: '#d1cbc9', gloss: true, type: 'shade'},

  {name: 'Poxwalker', hex: '#5c9c9f', hex2: '#cdd1ce', gloss: true, type: 'shade'},
  {name: 'Mortarion Grime', hex: '#b3a811', hex2: '#d7d1b3', gloss: true, type: 'shade'},
  {name: 'Kroak Green', hex: '#87c299', hex2: '#cfd5cb', gloss: true, type: 'shade'},
  {name: 'Berserker Bloodshade', hex: '#bc1e4e', hex2: '#d9babf', gloss: true, type: 'shade'},
  {name: 'Targor Rageshade', hex: '#716074', hex2: '#d2cbca', gloss: true, type: 'shade'},
  {name: 'Soulblight Grey', hex: '#a8a3a7', hex2: '#d9d4d1', gloss: true, type: 'shade'},
  {name: 'Tyran Blue', hex: '#1a8dcb', hex2: '#b7cad4', gloss: true, type: 'shade'},


  // {name: "Praxeti White", "hex": "#FFFFFF", type: "dry"},
  // {name: "Wrack White", "hex": "#d3d0cf", type: "dry"},
  // {name: "Hexos Palesun", "hex": "#fff55a", type: "dry"},
  // {name: "Kindleflame", "hex": "#f69c82", type: "dry"},
  // {name: "Ryza Rust", "hex": "#f16c22", type: "dry"},
  // {name: "Astorath Red", "hex": "#a9311e", type: "dry"},
  // {name: "Changeling Pink", "hex": "#f3abca", type: "dry"},
  // {name: "Lucius Lilac", "hex": "#b498c9", type: "dry"},
  // {name: "Slaanesh Grey", "hex": "#8b8893", type: "dry"},
  // {name: "Skink Blue", "hex": "#54bdca", type: "dry"},
  // {name: "Etherium Blue", "hex": "#9eb5ce", type: "dry"},
  // {name: "Hoeth Blue", "hex": "#4c78af", type: "dry"},
  // {name: "Stormfang", "hex": "#5a7fa3", type: "dry"},
  // {name: "Imrik Blue", "hex": "#208abf", type: "dry"},
  // {name: "Chronus Blue", "hex": "#4b90cf", type: "dry"},
  // {name: "Thunderhawk Blue", "hex": "#396a70", type: "dry"},
  // {name: "Hellion Green", "hex": "#7fc1a5", type: "dry"},
  // {name: "Nurgling Green", "hex": "#7e975e", type: "dry"},
  // {name: "Niblet Green", "hex": "#378c35", type: "dry"},
  // {name: "Underhive Ash", "hex": "#bcbb7e", type: "dry"},
  // {name: "Tyrant Skull", "hex": "#c8c482", type: "dry"},
  // {name: "Terminatus Stone", "hex": "#c8b79d", type: "dry"},
  // {name: "Golgfag Brown", "hex": "#8f502a", type: "dry"},
  // {name: "Sylvaneth Bark", "hex": "#4e483b", type: "dry"},
  // {name: "Verminlord Hide", "hex": "#7e3231", type: "dry"},
  // {name: "Eldar Flesh", "hex": "#e8c07f", type: "dry"},
  // {name: "Longbeard Grey", "hex": "#dbdcc6", type: "dry"},
  // {name: "Dawnstone", "hex": "#697068", type: "dry"},
  // {name: "Necron Compound", "hex": "#bdc1c4", "hex2": "#f7f7f8", type: "dry"},
  // {name: "Sigmarite", "hex": "#cc9947", "hex2": "#f3c770", type: "dry"},
  // {name: "Golden Griffon", "hex": "#b18a48", "hex2": "#FFFFFF", type: "dry"},


  {name: 'Martian Ironcrust', hex: '#9b5041', image: 'MartianIroncrust.svg', type: 'basing'},
  {name: 'Mordant Earth', hex: '#4b4849', image: 'MordantEarth.svg', type: 'basing'},
  {name: 'Astrogranite', hex: '#767675', image: 'Astrogranite.svg', type: 'basing'},
  {name: 'Astrogranite Debris', hex: '#767675', image: 'AstrograniteDebris.svg', type: 'basing'},
  {name: 'Valhallan Blizzard', hex: '#FFFFFF', image: 'ValhallanBlizzard.svg', type: 'basing'},
  {name: 'Armageddon Dunes', hex: '#d2ad00', image: 'ArmageddonDunes.svg', type: 'basing'},
  {name: 'Armageddon Dust', hex: '#d2ad00', image: 'ArmageddonDust.svg', type: 'basing'},
  {name: 'Martian Ironearth', hex: '#9b5041', image: 'MartianIronearth.svg', type: 'basing'},
  {name: 'Agrellan Earth', hex: '#938165', image: 'AgrellanEarth.svg', type: 'basing'},
  {name: 'Agrellan Badland', hex: '#938165', image: 'AgrellanBadland.svg', type: 'basing'},
  {name: 'Stirland Battlemire', hex: '#482b00', image: 'StirlandBattlemire.svg', type: 'basing'},
  {name: 'Stirland Mud', hex: '#482b00', image: 'StirlandMud.svg', type: 'basing'},


  {name: 'Typhus Corrosion', hex: '#373a22', type: 'technical'},
  {name: 'Nurgle\'s Rot', hex: '#9d8b16', type: 'technical'},
  {name: 'Hexwraith Flame', hex: '#139229', type: 'technical'},
  {name: 'Nihilakh Oxide', hex: '#66b39a', type: 'technical'},
  {name: 'Tesseract Glow', hex: '#49AD33', type: 'technical'},
  {name: 'Blood for the Blood God', hex: '#4c0007', gloss: true, type: 'technical'},
  {name: 'Spiritstone Red', hex: '#7c1000', gloss: true, type: 'technical'},
  {name: 'Solar Anomalie', hex: '#C554AC', hex2: '#C6D11B', brand: 'gsw', type: 'technical'},
  {name: 'Nighthaunt Gloom', hex: '#3d7177', type: 'technical'},
  {name: 'Waystone Green', hex: '#00371f', gloss: true, type: 'technical'},
  {name: 'Soulstone Blue', hex: '#01154b', gloss: true, type: 'technical'},


  {name: '\'Ardcoat', hex: '#ebebeb', hex2: '#FFFFFF', gloss: true, type: 'auxilliary'},
  {name: 'Contrast Medium', hex: '#ebebeb', hex2: '#FFFFFF', type: 'auxilliary'},
  {name: 'Lahmian Medium', hex: '#ebebeb', hex2: '#FFFFFF', type: 'auxilliary'},
  {name: 'Stormshield', hex: '#ebebeb', hex2: '#FFFFFF', type: 'auxilliary'},
  {name: 'Flow Enhancer', hex: '#ebebeb', hex2: '#FFFFFF', type: 'auxilliary'},
  {name: 'Thinner Medium', hex: '#ebebeb', hex2: '#FFFFFF', type: 'auxilliary'},
  {name: 'Paint Retarder', hex: '#ebebeb', hex2: '#FFFFFF', type: 'auxilliary'},


  {name: 'Air Caste Thinner', 'hex': '#ebebeb', 'hex2': '#FFFFFF', type: 'air'},
  {name: 'White Scar', 'hex': '#FFFFFF', type: 'air'},
  {name: 'Ulthuan Grey', 'hex': '#c4ddd5', type: 'air'},
  {name: 'Phalanx Yellow', 'hex': '#875408', type: 'air'},
  {name: 'Flash Gitz Yellow', 'hex': '#fff300', type: 'air'},
  {name: 'Sigismund Yellow Clear', 'hex': '#ffe32f', type: 'air'},
  {name: 'Averland Sunset', 'hex': '#fbb81c', type: 'air'},
  {name: 'Troll Slayer Orange', 'hex': '#f16c22', type: 'air'},
  {name: 'Evil Sunz Scarlet', 'hex': '#c01411', type: 'air'},
  {name: 'Mephiston Red', 'hex': '#960c09', type: 'air'},
  {name: 'Khorne Red', 'hex': '#650001', type: 'air'},
  {name: 'Word Bearers Red', 'hex': '#4c0005', type: 'air'},
  {name: 'Gal Vorbak Red', 'hex': '#4b213c', type: 'air'},
  {name: 'Kakophoni Purple', 'hex': '#8869ae', type: 'air'},
  {name: 'Genestealer Purple', 'hex': '#7658a5', type: 'air'},
  {name: 'Chemos Purple', 'hex': '#4f356c', type: 'air'},
  {name: 'Phoenician Purple', 'hex': '#440052', type: 'air'},
  {name: 'Lothern Blue', 'hex': '#2c9bcc', type: 'air'},
  {name: 'Calgar Blue', 'hex': '#29497f', type: 'air'},
  {name: 'Caledor Sky', 'hex': '#366699', type: 'air'},
  {name: 'Macragge Blue', 'hex': '#0e3d7c', type: 'air'},
  {name: 'Kantor Blue', 'hex': '#02124e', type: 'air'},
  {name: 'Night Lords Blue', 'hex': '#002b5b', type: 'air'},
  {name: 'Temple Guard Blue', 'hex': '#239489', type: 'air'},
  {name: 'Sybarite Green', 'hex': '#17a166', type: 'air'},
  {name: 'Lupercal Green', 'hex': '#002c2b', type: 'air'},
  {name: 'Ogryn Camo', 'hex': '#96a648', type: 'air'},
  {name: 'Elysian Green', 'hex': '#6b8c37', type: 'air'},
  {name: 'Straken Green', 'hex': '#597f1b', type: 'air'},
  {name: 'Deathworld Forest', 'hex': '#556228', type: 'air'},
  {name: 'Castellan Green', 'hex': '#264715', type: 'air'},
  {name: 'Death Korps Drab', 'hex': '#3d4539', type: 'air'},
  // {name: "Sons of Horus Green", "hex": "#00545e", type: "air"},
  // {name: "Vulkan Green", "hex": "#223c2e", type: "air"},
  // {name: "Moot Green", "hex": "#3cae44", type: "air"},
  // {name: "Warboss Green", "hex": "#307e57", type: "air"},
  // {name: "Caliban Green", "hex": "#003d15", type: "air"},
  // {name: "Nocturne Green", "hex": "#152a29", type: "air"},
  // {name: "Ushabti Bone", "hex": "#aba172", type: "air"},
  // {name: "Terminatus Stone", "hex": "#c8b79d", type: "air"},
  // {name: "Typhon Ash", "hex": "#e4d8c1", type: "air"},
  // {name: "Karak Stone", "hex": "#b7945c", type: "air"},
  // {name: "Baneblade Brown", "hex": "#8e7c68", type: "air"},
  // {name: "Tau Light Ochre", "hex": "#bc6b0f", type: "air"},
  // {name: "Pyroclast Orange Clear", "hex": "#ed8022", type: "air"},
  // {name: "Angron Red Clear", "hex": "#e11823", type: "air"},
  // {name: "Eidolon Purple Clear", "hex": "#7d4d99", type: "air"},
  // {name: "Calth Blue Clear", "hex": "#0086d1", type: "air"},
  // {name: "Fenrisian Grey", "hex": "#6d93b3", type: "air"},
  // {name: "Russ Grey", "hex": "#507085", type: "air"},
  // {name: "The Fang", "hex": "#405b71", type: "air"},
  // {name: "Mortarion Green Clear", "hex": "#00832b", type: "air"},
  // {name: "Dryad Bark", "hex": "#2b2a24", type: "air"},
  // {name: "Steel Legion Drab", "hex": "#584e2d", type: "air"},
  // {name: "XV-88", "hex": "#6c4810", type: "air"},
  // {name: "Balor Brown", "hex": "#875408", type: "air"},
  // {name: "Tallarn Sand", "hex": "#a07407", type: "air"},
  // {name: "Mournfang Brown", "hex": "#490e06", type: "air"},
  // {name: "Tuskgor Fur", "hex": "#863231", type: "air"},
  // {name: "Deathclaw Brown", "hex": "#af634e", type: "air"},
  // {name: "Kislev Flesh", "hex": "#d1a470", type: "air"},
  // {name: "Zandri Dust", "hex": "#988e56", type: "air"},
  // {name: "Administratum Grey", "hex": "#8f9690", type: "air"},
  // {name: "Dawnstone", "hex": "#697068", type: "air"},
  // {name: "Mechanicus Standard Grey", "hex": "#38484a", type: "air"},
  // {name: "Deathshroud Clear", "hex": "#1c1c1b", type: "air"},
  // {name: "Corvus Black", "hex": "#171314", type: "air"},
  // {name: "Abaddon Black", "hex": "#000000", type: "air"},
  // {name: "Balthasar Gold", "hex": "#5d3c29", "hex2": "#fbbe87", metallic: true, type: "air"},
  // {name: "Thallax Gold", "hex": "#ac5724", "hex2": "#ffe696", metallic: true, type: "air"},
  // {name: "Valdor Gold", "hex": "#9b5428", "hex2": "#e5d4c5", metallic: true, type: "air"},
  // {name: "Relictor Gold", "hex": "#b79152", "hex2": "#FFFFFF", metallic: true, type: "air"},
  // {name: "Iron Hands Steel", "hex": "#7b736e", "hex2": "#FFFFFF", metallic: true, type: "air"},
  // {name: "Ironbreaker", "hex": "#5d6061", "hex2": "#FFFFFF", metallic: true, type: "air"},
  // {name: "Leadbelcher", "hex": "#515658", "hex2": "#FFFFFF", metallic: true, type: "air"},
  // {name: "Grey Knights Steel", "hex": "#788993", "hex2": "#FFFFFF", metallic: true, type: "air"},
  // {name: "Runefang Steel", "hex": "#9ba2a5", "hex2": "#FFFFFF", metallic: true, type: "air"},
  // {name: "Castellax Bronze", "hex": "#7e3e1f", "hex2": "#FFFFFF", metallic: true, type: "air"},

  // Pro-acryl Colors
  {name: 'Bronze', hex: '#443a1a', hex2: '#7f794c', metallic: true, type: 'base'},
  {name: 'Copper', hex: '#72320f', hex2: '#b07048', metallic: true, type: 'base'},
  {name: 'Light Bronze', hex: '#585b2d', hex2: '#abab70', metallic: true, type: 'base'},
  {name: 'Dark Silver', hex: '#101c1c', hex2: '#415555', metallic: true, type: 'base'},
  {name: 'Silver', hex: '#7d8688', hex2: '#cfdadd', metallic: true, type: 'base'},
  {name: 'White Gold', hex: '#7c8168', hex2: '#c0c7a7', metallic: true, type: 'base'},

  // Two-thin Coats
  {name: 'Dragon\'s Gold', hex: '#a26e29', hex2: '#FFFFFF', metallic: true, type: 'base'},
  {name: 'Doom Death Black', hex: '#3d3937', type: 'base'},
]

