import './App.css';
import {Section} from "./Section";

const data = {
  "base": [
    {"name": "Corax White", "hex": "#FFFFFF"},
    {"name": "Grey Seer", "hex": "#919496"},
    {"name": "Celestra Grey", "hex": "#9fadad"},
    {"name": "Averland Sunset", "hex": "#e9b929"},
    {"name": "Jokaero Orange", "hex": "#c52f17"},
    {"name": "Khorne Red", "hex": "#5b1201"},
    {"name": "Mephiston Red", "hex": "#841710"},
    {"name": "Gal Vorbak Red", "hex": "#39172e"},
    {"name": "Barak-Nar Burgundy", "hex": "#330f27"},
    {"name": "Screamer Pink", "hex": "#701e42"},
    {"name": "Daemonette Hide", "hex": "#716d88"},
    {"name": "Phoenician Purple", "hex": "#330041"},
    {"name": "Naggaroth Night", "hex": "#423954"},
    {"name": "Caledor Sky", "hex": "#4b6797"},
    {"name": "Macragge Blue", "hex": "#283c77"},
    {"name": "Kantor Blue", "hex": "#19284f"},
    {"name": "Night Lords Blue", "hex": "#021e49"},
    {"name": "Thousand Sons Blue", "hex": "#083b59"},
    {"name": "Stegadon Scale Green", "hex": "#254460"},
    {"name": "Lupercal Green", "hex": "#022120"},
    {"name": "Incubi Darkness", "hex": "#294548"},
    {"name": "Death Guard Green", "hex": "#5a653c"},
    {"name": "Death World Forest", "hex": "#686d35"},
    {"name": "Castellan Green", "hex": "#424e28"},
    {"name": "Death Korps Drap", "hex": "#2f362b"},
    {"name": "Waaagh! Flesh", "hex": "#3c572e"},
    {"name": "Caliban Green", "hex": "#193c24"},
    {"name": "Nocturne Green", "hex": "#11201f"},
    {"name": "Wraithbone", "hex": "#d3c8a2"},
    {"name": "Morghast Bone", "hex": "#b29960"},
    {"name": "Zandri Dust", "hex": "#a2985d"},
    {"name": "XV-88", "hex": "#6f4e25"},
    {"name": "Steel Legion Drab", "hex": "#645639"},
    {"name": "Mournfang Brown", "hex": "#5a180a"},
    {"name": "Rhinox Hide", "hex": "#493735"},
    {"name": "Dryad Bark", "hex": "#3b3833"},
    {"name": "Ionrach Skin", "hex": "#859371"},
    {"name": "Rakarth Flesh", "hex": "#a8a294"},
    {"name": "Ratskin Flesh", "hex": "#a26b4c"},
    {"name": "Bugman's Glow", "hex": "#7e5247"},
    {"name": "Catachan Fleshtone", "hex": "#34201b"},
    {"name": "The Fang", "hex": "#536579"},
    {"name": "Mechanicus Standard Grey", "hex": "#485052"},
    {"name": "Corvus Black", "hex": "#120f10"},
    {"name": "Abaddon Black", "hex": "#000000"},
    {"name": "Grey Knights Steel", "hex": "#62727d", "hex2": "#FFFFFF", "metallic": true},
    {"name": "Iron Hands Steel", "hex": "#605a55", "hex2": "#FFFFFF", "metallic": true},
    {"name": "Leadbelcher", "hex": "#4c4d51", "hex2": "#FFFFFF", "metallic": true},
    {"name": "Iron Warriors", "hex": "#353431", "hex2": "#FFFFFF", "metallic": true},
    {"name": "Retributor Armor", "hex": "#a26e29", "hex2": "#FFFFFF", "metallic": true},
    {"name": "Balthasar Gold", "hex": "#6b3f12", "hex2": "#FFFFFF", "metallic": true},
    {"name": "Screaming Bell", "hex": "#9a4411", "hex2": "#FFFFFF", "metallic": true},
    {"name": "Warplock Bronze", "hex": "#4f3a3f", "hex2": "#FFFFFF", "metallic": true}
  ],
  "contrast": [
    {"name": "Apothecary White", "hex": "#91afc9",  "hex2": "#eef4fa"},
    {"name": "Iyanden Yellow", "hex": "#d46e04",  "hex2": "#f7c024"},
    {"name": "Nazdreg Yellow", "hex": "#593e00",  "hex2": "#c58c00"},
    {"name": "Gryph-Hound Orange", "hex": "#842705",  "hex2": "#df5b30"},
    {"name": "Blood Angels Red", "hex": "#78080c",  "hex2": "#bb1318"},
    {"name": "Flesh Tearers Red", "hex": "#3d0100",  "hex2": "#7f0c09"},
    {"name": "Volupus Pink", "hex": "#580014",  "hex2": "#89023d"},
    {"name": "Magos Purple", "hex": "#682559",  "hex2": "#bc9ebc"},
    {"name": "Shyish Purple", "hex": "#200239",  "hex2": "#503864"},
    {"name": "Talassar Blue", "hex": "#002e5b",  "hex2": "#006eba"},
    {"name": "Ultramarines Blue", "hex": "#010c3a",  "hex2": "#264b81"},
    {"name": "Leviadon Blue", "hex": "#010407",  "hex2": "#01284f"},
    {"name": "Space Wolves Grey", "hex": "#043054",  "hex2": "#7898b4"},
    {"name": "Gryph-Charger Grey", "hex": "#045177",  "hex2": "#9abdd0"},
    {"name": "Aethermatic Blue", "hex": "#026f84",  "hex2": "#7ab7c3"},
    {"name": "Akhelian Green", "hex": "#004759",  "hex2": "#007795"},
    {"name": "Terradon Turquoise", "hex": "#004c54",  "hex2": "#008398"},
    {"name": "Plaguebearer Flesh", "hex": "#5d6e08",  "hex2": "#bfc697"},
    {"name": "Warp Lightning", "hex": "#00511c",  "hex2": "#00914a"},
    {"name": "Ork Flesh", "hex": "#01501b",  "hex2": "#007e29"},
    {"name": "Militarum Green", "hex": "#626f04",  "hex2": "#929746"},
    {"name": "Creed Camo", "hex": "#095524",  "hex2": "#528b68"},
    {"name": "Dark Angels Green", "hex": "#000202",  "hex2": "#01473f"},
    {"name": "Skeleton Horde", "hex": "#94855d",  "hex2": "#e5dbbb"},
    {"name": "Aggaros Dunes", "hex": "#584f38",  "hex2": "#beae64"},
    {"name": "Gore-Grunta Fur", "hex": "#563925",  "hex2": "#863f07"},
    {"name": "Wyldwood", "hex": "#3c211a",  "hex2": "#674c47"},
    {"name": "Guilliman Flesh", "hex": "#923023",  "hex2": "#cc988b"},
    {"name": "Fyreslayer Flesh", "hex": "#604332",  "hex2": "#b77563"},
    {"name": "Darkoath Flesh", "hex": "#895451",  "hex2": "#cb8e7e"},
    {"name": "Cygor Brown", "hex": "#33100e",  "hex2": "#6f4441"},
    {"name": "Snakebite Leather", "hex": "#5a462f",  "hex2": "#a66613"},
    {"name": "Basilicanum Grey", "hex": "#070707",  "hex2": "#8f8f8e"},
    {"name": "Black Templar", "hex": "#050505",  "hex2": "#636362"}
  ],
  "layer": [
    {"name": "White Scar", "hex": "#FFFFFF"},
    {"name": "Ulthuan Grey", "hex": "#c4ddd5"},
    {"name": "Dorn Yellow", "hex": "#fff55a"},
    {"name": "Phalanx Yellow", "hex": "#ffe200"},
    {"name": "Flash Gitz Yellow", "hex": "#fff300"},
    {"name": "Yriel Yellow", "hex": "#ffd801"},
    {"name": "Lugganath Orange", "hex": "#f69b82"},
    {"name": "Fire Dragon Bright", "hex": "#f4874e"},
    {"name": "Troll Slayer Orange", "hex": "#f16c22"},
    {"name": "Squig Orange", "hex": "#a74d41"},
    {"name": "Wild Rider Red", "hex": "#e82d1b"},
    {"name": "Evil Sunz Scarlet", "hex": "#c01411"},
    {"name": "Wazdakka Red", "hex": "#880803"},
    {"name": "Word Bearers Red", "hex": "#b74073"},
    {"name": "Fulgrim Pink", "hex": "#f3abca"},
    {"name": "Emperor's Children", "hex": "#b74073"},
    {"name": "Pink Horror", "hex": "#8d2657"},
    {"name": "Slaanesh Grey", "hex": "#8b8893"},
    {"name": "Warpfiend Grey", "hex": "#66656e"},
    {"name": "Dechala Lilac", "hex": "#b498c9"},
    {"name": "Kakophoni Purple", "hex": "#8869ae"},
    {"name": "Genestealer Purple", "hex": "#7658a5"},
    {"name": "Xereus Purple", "hex": "#47125a"},
    {"name": "Blue Horror", "hex": "#9eb5ce"},
    {"name": "Hoeth Blue", "hex": "#4c78af"},
    {"name": "Lothern Blue", "hex": "#2c9bcc"},
    {"name": "Calgar Blue", "hex": "#29497f"},
    {"name": "Teclis Blue", "hex": "#3777bf"},
    {"name": "Alaitoc Blue", "hex": "#2e4f85"},
    {"name": "Altdorf Guard Blue", "hex": "#2c4696"},
    {"name": "Baharroth Blue", "hex": "#54bdca"},
    {"name": "Temple Guard Blue", "hex": "#239489"},
    {"name": "Ahriman Blue", "hex": "#00708a"},
    {"name": "Sotek Green", "hex": "#0b6371"},
    {"name": "Gauss Blaster Green", "hex": "#7fc1a5"},
    {"name": "Sybarite Green", "hex": "#17a166"},
    {"name": "Kabalite Green", "hex": "#008962"},
    {"name": "Nurgling Green", "hex": "#7e975e"},
    {"name": "Elysian Green", "hex": "#6b8c37"},
    {"name": "Ogryn Camo", "hex": "#96a648"},
    {"name": "Straken Green", "hex": "#597f1b"},
    {"name": "Loren Forest", "hex": "#486c24"},
    {"name": "Sons of Horus Green", "hex": "#00545e"},
    {"name": "Vulkan Green", "hex": "#223c2e"},
    {"name": "Skarsnik Green", "hex": "#588f6b"},
    {"name": "Moot Green", "hex": "#3cae44"},
    {"name": "Warboss Green", "hex": "#307e57"},
    {"name": "Warpstone Glow", "hex": "#0e7029"},
    {"name": "Screaming Skull", "hex": "#b9c099"},
    {"name": "Ushabti Bone", "hex": "#aba172"},
    {"name": "Krieg Khaki", "hex": "#bcbb7e"},
    {"name": "Karak Stone", "hex": "#b7945c"},
    {"name": "Baneblade Brown", "hex": "#8e7c68"},
    {"name": "Gorthor Brown", "hex": "#5f463f"},
    {"name": "Zamesi Desert", "hex": "#d89d1a"},
    {"name": "Tallarn Sand", "hex": "#a07407"},
    {"name": "Deathclaw Brown", "hex": "#af634e"},
    {"name": "Balor Brown", "hex": "#875408"},
    {"name": "Tau Light Ochre", "hex": "#bc6b0f"},
    {"name": "Skrag Brown", "hex": "#8b4805"},
    {"name": "Tuskgor Fur", "hex": "#863231"},
    {"name": "Doombull Brown", "hex": "#570003"},
    {"name": "Pallid Wych Flesh", "hex": "#caccbb"},
    {"name": "Deepkin Flesh", "hex": "#a9b79f"},
    {"name": "Flayed One Flesh", "hex": "#eec483"},
    {"name": "Ungor Flesh", "hex": "#d1a560"},
    {"name": "Kislev Flesh", "hex": "#d1a470"},
    {"name": "Bestigor Flesh", "hex": "#cf8951"},
    {"name": "Cadian Fleshtone", "hex": "#c47652"},
    {"name": "Knight-Questor Flesh", "hex": "#996563"},
    {"name": "Bloodreaver Flesh", "hex": "#6a4847"},
    {"name": "Fenrisian Grey", "hex": "#6d93b3"},
    {"name": "Russ Grey", "hex": "#507085"},
    {"name": "Thunderhawk Blue", "hex": "#396a70"},
    {"name": "Dark Reaper", "hex": "#354d4c"},
    {"name": "Administratum Grey", "hex": "#989c94"},
    {"name": "Dawnstone", "hex": "#697068"},
    {"name": "Stormvermin Fur", "hex": "#6d655f"},
    {"name": "Eshin Grey", "hex": "#484b4e"},
    {"name": "Skavenblight Dinge", "hex": "#45413b"},
    {"name": "Stormhost Silver", "hex": "#b6bbbe",  "hex2": "#FFFFFF", "metallic": true},
    {"name": "Runefang Steel", "hex": "#989ea2",  "hex2": "#FFFFFF", "metallic": true},
    {"name": "Ironbreaker", "hex": "#5d6162",  "hex2": "#FFFFFF", "metallic": true},
    {"name": "Liberator Gold", "hex": "#b28b49",  "hex2": "#FFFFFF", "metallic": true},
    {"name": "Auric Armour Gold", "hex": "#e29a36",  "hex2": "#FFFFFF", "metallic": true},
    {"name": "Gehenna's Gold", "hex": "#97420f",  "hex2": "#fccd31", "metallic": true},
    {"name": "Fulgurite Copper", "hex": "#954f26",  "hex2": "#FFFFFF", "metallic": true},
    {"name": "Hashut Copper", "hex": "#7b4d2f",  "hex2": "#fccd88", "metallic": true},
    {"name": "Skullcrusher Brass", "hex": "#d8a352",  "hex2": "#FFFFFF", "metallic": true},
    {"name": "Runelord Brass", "hex": "#493a2c",  "hex2": "#FFFFFF", "metallic": true},
    {"name": "Brass Scorpion", "hex": "#713013",  "hex2": "#f7ba62", "metallic": true},
    {"name": "Sycorax Bronze", "hex": "#866251",  "hex2": "#FFFFFF", "metallic": true},
    {"name": "Castellax Bronze", "hex": "#723419",  "hex2": "#FFFFFF", "metallic": true},
  ],
  "shade": [
    {"name": "Cassandora Yellow", "hex": "#e8843a",  "hex2": "#fbe9b4"},
    {"name": "Fuegan Orange", "hex": "#712107",  "hex2": "#d99863"},
    {"name": "Carroburg Crimson", "hex": "#390f10",  "hex2": "#f3aedf"},
    {"name": "Druchii Violet", "hex": "#2a0f2d",  "hex2": "#b989bc"},
    {"name": "Drakenhof Nightshade", "hex": "#121b22",  "hex2": "#dbdde7"},
    {"name": "Coelia Greenshade", "hex": "#113834",  "hex2": "#1eb2a7"},
    {"name": "Biel-Tan Green", "hex": "#1a3527",  "hex2": "#a6d39c"},
    {"name": "Athonian Camoshade", "hex": "#262517",  "hex2": "#f6f7b9"},
    {"name": "Seraphim Sepia", "hex": "#35240c",  "hex2": "#e0a777"},
    {"name": "Reikland Fleshshade Gloss", "hex": "#371f0e",  "hex2": "#f3caad", "gloss": true},
    {"name": "Reikland Fleshshade", "hex": "#371f0e",  "hex2": "#f3caad"},
    {"name": "Agrax Earthshade", "hex": "#382517",  "hex2": "#d7cebd"},
    {"name": "Agrax Earthshade Gloss", "hex": "#382517",  "hex2": "#d7cebd", "gloss": true},
    {"name": "Nuln Oil", "hex": "#1c1c1b",  "hex2": "#d1cbc9"},
    {"name": "Nuln Oil Gloss", "hex": "#1c1c1b",  "hex2": "#d1cbc9", "gloss": true}
  ],
  "dry": [
    {"name": "Praxeti White", "hex": "#FFFFFF"},
    {"name": "Wrack White", "hex": "#d3d0cf"},
    {"name": "Hexos Palesun", "hex": "#fff55a"},
    {"name": "Kindleflame", "hex": "#f69c82"},
    {"name": "Ryza Rust", "hex": "#f16c22"},
    {"name": "Astorath Red", "hex": "#a9311e"},
    {"name": "Changeling Pink", "hex": "#f3abca"},
    {"name": "Lucius Lilac", "hex": "#b498c9"},
    {"name": "Slaanesh Grey", "hex": "#8b8893"},
    {"name": "Skink Blue", "hex": "#54bdca"},
    {"name": "Etherium Blue", "hex": "#9eb5ce"},
    {"name": "Hoeth Blue", "hex": "#4c78af"},
    {"name": "Stormfang", "hex": "#5a7fa3"},
    {"name": "Imrik Blue", "hex": "#208abf"},
    {"name": "Chronus Blue", "hex": "#4b90cf"},
    {"name": "Thunderhawk Blue", "hex": "#396a70"},
    {"name": "Hellion Green", "hex": "#7fc1a5"},
    {"name": "Nurgling Green", "hex": "#7e975e"},
    {"name": "Niblet Green", "hex": "#378c35"},
    {"name": "Underhive Ash", "hex": "#bcbb7e"},
    {"name": "Tyrant Skull", "hex": "#c8c482"},
    {"name": "Terminatus Stone", "hex": "#c8b79d"},
    {"name": "Golgfag Brown", "hex": "#8f502a"},
    {"name": "Sylvaneth Bark", "hex": "#4e483b"},
    {"name": "Verminlord Hide", "hex": "#7e3231"},
    {"name": "Eldar Flesh", "hex": "#e8c07f"},
    {"name": "Longbeard Grey", "hex": "#dbdcc6"},
    {"name": "Dawnstone", "hex": "#697068"},
    {"name": "Necron Compound", "hex": "#bdc1c4",  "hex2": "#f7f7f8"},
    {"name": "Sigmarite", "hex": "#cc9947",  "hex2": "#f3c770"},
    {"name": "Golden Griffon", "hex": "#b18a48",  "hex2": "#FFFFFF"}
  ],
  "technical": [
    {"name": "Contrast Medium", "hex": "#ebebeb",  "hex2": "#FFFFFF"},
    {"name": "Lahmian Medium", "hex": "#ebebeb",  "hex2": "#FFFFFF"},
    {"name": "Armageddon Dunes", "hex": "#d2ad00",  "image": "ArmageddonDunes.svg"},
    {"name": "Armageddon Dust", "hex": "#d2ad00",  "image": "ArmageddonDust.svg"},
    {"name": "Martian Ironcrust", "hex": "#9b5041",  "image": "MartianIroncrust.svg"},
    {"name": "Martian Ironearth", "hex": "#9b5041",  "image": "MartianIronearth.svg"},
    {"name": "Agrellan Earth", "hex": "#938165",  "image": "AgrellanEarth.svg"},
    {"name": "Agrellan Badland", "hex": "#938165",  "image": "AgrellanBadland.svg"},
    {"name": "Stirland Battlemire", "hex": "#482b00",  "image": "StirlandBattlemire.svg"},
    {"name": "Stirland Mud", "hex": "#482b00",  "image": "StirlandMud.svg"},
    {"name": "Mordant Earth", "hex": "#4b4849",  "image": "MordantEarth.svg"},
    {"name": "Typhus Corrosion", "hex": "#373a22"},
    {"name": "Nurgles Rot", "hex": "#9d8b16"},
    {"name": "Valhallan Blizzard", "hex": "#FFFFFF",  "image": "ValhallanBlizzard.svg"},
    {"name": "Stormshield", "hex": "#ebebeb",  "hex2": "#FFFFFF"},
    {"name": "Astrogranite", "hex": "#767675",  "image": "Astrogranite.svg"},
    {"name": "Astrogranite Debris", "hex": "#767675",  "image": "AstrograniteDebris.svg"},
    {"name": "Nighthaunt gloom", "hex": "#3d7177"},
    {"name": "Hexwraith flame", "hex": "#139229"},
    {"name": "Nihilakh Oxide", "hex": "#66b39a"},
    {"name": "'Ardcoat", "hex": "#ebebeb",  "hex2": "#FFFFFF", "gloss": true},
    {"name": "Blood for the blood god", "hex": "#4c0007",  "gloss": true},
    {"name": "Spiritstone Red", "hex": "#7c1000",  "gloss": true},
    {"name": "Waystone Green", "hex": "#00371f",  "gloss": true},
    {"name": "Soulstone Blue", "hex": "#01154b",  "gloss": true},

      // Own paints
    {"name": "Solar Anomalie", "hex": "#C554AC", "hex2": "#C6D11B"}
  ],
  "air": [
    {"name": "Air Caste Thinner", "hex": "#ebebeb",  "hex2": "#FFFFFF"},
    {"name": "White Scar", "hex": "#FFFFFF"},
    {"name": "Ulthuan Grey", "hex": "#c4ddd5"},
    {"name": "Phalanx Yellow", "hex": "#875408"},
    {"name": "Flash Gitz Yellow", "hex": "#fff300"},
    {"name": "Sigismund Yellow Clear", "hex": "#ffe32f"},
    {"name": "Averland Sunset", "hex": "#fbb81c"},
    {"name": "Troll Slayer Orange", "hex": "#f16c22"},
    {"name": "Evil Sunz Scarlet", "hex": "#c01411"},
    {"name": "Mephiston Red", "hex": "#960c09"},
    {"name": "Khorne Red", "hex": "#650001"},
    {"name": "Word Bearers Red", "hex": "#4c0005"},
    {"name": "Gal Vorbak Red", "hex": "#4b213c"},
    {"name": "Kakophoni Purple", "hex": "#8869ae"},
    {"name": "Genestealer Purple", "hex": "#7658a5"},
    {"name": "Chemos Purple", "hex": "#4f356c"},
    {"name": "Phoenician Purple", "hex": "#440052"},
    {"name": "Lothern Blue", "hex": "#2c9bcc"},
    {"name": "Calgar Blue", "hex": "#29497f"},
    {"name": "Caledor Sky", "hex": "#366699"},
    {"name": "Macragge Blue", "hex": "#0e3d7c"},
    {"name": "Kantor Blue", "hex": "#02124e"},
    {"name": "Night Lords Blue", "hex": "#002b5b"},
    {"name": "Temple Guard Blue", "hex": "#239489"},
    {"name": "Sybarite Green", "hex": "#17a166"},
    {"name": "Lupercal Green", "hex": "#002c2b"},
    {"name": "Ogryn Camo", "hex": "#96a648"},
    {"name": "Elysian Green", "hex": "#6b8c37"},
    {"name": "Straken Green", "hex": "#597f1b"},
    {"name": "Deathworld Forest", "hex": "#556228"},
    {"name": "Castellan Green", "hex": "#264715"},
    {"name": "Death Korps Drab", "hex": "#3d4539"},
    {"name": "Sons of Horus Green", "hex": "#00545e"},
    {"name": "Vulkan Green", "hex": "#223c2e"},
    {"name": "Moot Green", "hex": "#3cae44"},
    {"name": "Warboss Green", "hex": "#307e57"},
    {"name": "Caliban Green", "hex": "#003d15"},
    {"name": "Nocturne Green", "hex": "#152a29"},
    {"name": "Ushabti Bone", "hex": "#aba172"},
    {"name": "Terminatus Stone", "hex": "#c8b79d"},
    {"name": "Typhon Ash", "hex": "#e4d8c1"},
    {"name": "Karak Stone", "hex": "#b7945c"},
    {"name": "Baneblade Brown", "hex": "#8e7c68"},

    {"name": "Tau Light Ochre", "hex": "#bc6b0f"},
    {"name": "Pyroclast Orange Clear", "hex": "#ed8022"},
    {"name": "Angron Red Clear", "hex": "#e11823"},
    {"name": "Eidolon Purple Clear", "hex": "#7d4d99"},
    {"name": "Calth Blue Clear", "hex": "#0086d1"},
    {"name": "Fenrisian Grey", "hex": "#6d93b3"},
    {"name": "Russ Grey", "hex": "#507085"},
    {"name": "The Fang", "hex": "#405b71"},
    {"name": "Mortarion Green Clear", "hex": "#00832b"},
    {"name": "Dryad Bark", "hex": "#2b2a24"},
    {"name": "Steel Legion Drab", "hex": "#584e2d"},
    {"name": "XV-88", "hex": "#6c4810"},
    {"name": "Balor Brown", "hex": "#875408"},
    {"name": "Tallarn Sand", "hex": "#a07407"},
    {"name": "Mournfang Brown", "hex": "#490e06"},
    {"name": "Tuskgor Fur", "hex": "#863231"},
    {"name": "Deathclaw Brown", "hex": "#af634e"},
    {"name": "Kislev Flesh", "hex": "#d1a470"},
    {"name": "Zandri Dust", "hex": "#988e56"},
    {"name": "Administratum Grey", "hex": "#8f9690"},
    {"name": "Dawnstone", "hex": "#697068"},
    {"name": "Mechanicus Standard Grey", "hex": "#38484a"},
    {"name": "Deathshroud Clear", "hex": "#1c1c1b"},
    {"name": "Corvus Black", "hex": "#171314"},
    {"name": "Abaddon Black", "hex": "#000000"},
    {"name": "Balthasar Gold", "hex": "#5d3c29",  "hex2": "#fbbe87", "metallic": true},
    {"name": "Thallax Gold", "hex": "#ac5724",  "hex2": "#ffe696", "metallic": true},
    {"name": "Valdor Gold", "hex": "#9b5428",  "hex2": "#e5d4c5", "metallic": true},
    {"name": "Relictor Gold", "hex": "#b79152",  "hex2": "#FFFFFF", "metallic": true},
    {"name": "Iron Hands Steel", "hex": "#7b736e",  "hex2": "#FFFFFF", "metallic": true},
    {"name": "Ironbreaker", "hex": "#5d6061",  "hex2": "#FFFFFF", "metallic": true},
    {"name": "Leadbelcher", "hex": "#515658",  "hex2": "#FFFFFF", "metallic": true},
    {"name": "Grey Knights Steel", "hex": "#788993",  "hex2": "#FFFFFF", "metallic": true},
    {"name": "Runefang Steel", "hex": "#9ba2a5",  "hex2": "#FFFFFF", "metallic": true},
    {"name": "Castellax Bronze", "hex": "#7e3e1f",  "hex2": "#FFFFFF", "metallic": true},
  ]
}

function App() {
  const sections = Object.keys(data);

  return (
    <div className="App">
      <header className="App-header">
        {sections.map(sectionName => {
          return <Section key={sectionName} sectionName={sectionName} paints={data[sectionName]}/>
        })}
      </header>
    </div>
  );
}

export default App;
